# This is a basic workflow to help you get started with matillion ci/cd

name: Run matillion jobs 
on:  
    # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  pull_request:
    branches:
      - master

jobs:  
  sample1:
    runs-on: ubuntu-latest

   
